"""add currncy-log

Revision ID: 2583afe4e5de
Revises: 2f1cb861c503
Create Date: 2025-07-31 01:01:47.489371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2583afe4e5de"
down_revision: Union[str, None] = "2f1cb861c503"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('transaction_reports',
    # sa.Column('transaction_id', sa.Integer(), nullable=False),
    # sa.Column('reference', sa.String(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('status', sa.Enum('pending', 'completed', 'cancelled', name='transactionstatus'), nullable=True),
    # sa.Column('status_reason', sa.String(), nullable=True),
    # sa.Column('amount_foreign', sa.Float(), nullable=True),
    # sa.Column('amount_lyd', sa.Float(), nullable=True),
    # sa.Column('profit', sa.Float(), nullable=True),
    # sa.Column('customer_id', sa.Integer(), nullable=True),
    # sa.Column('customer_name', sa.String(), nullable=True),
    # sa.Column('customer_phone', sa.String(), nullable=True),
    # sa.Column('customer_city', sa.String(), nullable=True),
    # sa.Column('employee_id', sa.Integer(), nullable=True),
    # sa.Column('employee_username', sa.String(), nullable=True),
    # sa.Column('employee_full_name', sa.String(), nullable=True),
    # sa.Column('service_id', sa.Integer(), nullable=True),
    # sa.Column('service_name', sa.String(), nullable=True),
    # sa.Column('service_price', sa.Float(), nullable=True),
    # sa.Column('service_operation', sa.String(), nullable=True),
    # sa.Column('currency_id', sa.Integer(), nullable=True),
    # sa.Column('currency_name', sa.String(), nullable=True),
    # sa.Column('currency_symbol', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('transaction_id'),
    # info={'is_view': True}
    # )
    op.create_table(
        "currency_lot_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lot_id", sa.Integer(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("quantity_added", sa.Float(), nullable=False),
        sa.Column("cost_per_unit", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["currency_id"], ["currencies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lot_id"], ["currency_lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_currency_lot_logs_id"), "currency_lot_logs", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currency_lot_logs_id"), table_name="currency_lot_logs")
    op.drop_table("currency_lot_logs")
    # op.drop_table('transaction_reports')
    # ### end Alembic commands ###
